Development
LogNi-FinTech/logni-credit-service pull request #1
Opened 2023-01-12 18:29 UTC by Ibrahim-Khan88

2023-01-22 19:33 UTC, azomshahriar requested changes

2023-01-22 19:33 UTC, azomshahriar commented on src/main/java/com/logni/credit/service/controller/LoanAppliactionController.java
> +      } catch (IOException ex) {
Plz log the exception

2023-01-22 19:33 UTC, azomshahriar commented on src/main/java/com/logni/credit/service/controller/LoanController.java
> +   // todo update loan status
remove comment if done

2023-01-22 19:33 UTC, azomshahriar commented on src/main/java/com/logni/credit/service/controller/LoanController.java
> +      Optional<Loan> loanCreate = loanRepository.findById(loanReceived.getLoanId());
loanCreate -> createdLoan

2023-01-22 19:33 UTC, azomshahriar commented on src/main/java/com/logni/credit/service/controller/LoanProductController.java
> +	@PostMapping()
remove ()

2023-01-22 19:33 UTC, azomshahriar commented on src/main/java/com/logni/credit/service/controller/LoanProductController.java
> +		if (exist) {
loanProductRepository.findById(loanProductId).ifPresent(loanProductRepository::delete);

2023-01-22 19:33 UTC, azomshahriar commented on src/main/java/com/logni/credit/service/controller/LoanProductController.java
> +		if (exist) {
single line code

2023-01-22 19:33 UTC, azomshahriar commented on src/main/java/com/logni/credit/service/service/FileStorageService.java
> +                throw new RuntimeException("File not found " + fileName);
LoofiRuntimeException??

2023-02-05 18:25 UTC, Ibrahim-Khan88 commented on src/main/java/com/logni/credit/service/service/FileStorageService.java
> +                throw new RuntimeException("File not found " + fileName);
Resolved all issues

2023-08-14 04:38 UTC, merged